from .admin import ContactoAdmin
from .admin import FilaSeccionFotoInline
from .admin import FotoFilaSeccionFotoInline
from .admin import IdiomaAdmin
from .admin import ParametroAdmin
from .admin import SeccionFotoAdmin
from .admin import SeccionTextoAdmin
from .admin import SeccionTextoFotoAdmin
from .admin import SocialAdmin
from .admin import TextoContactoInline
from .admin import TextoFotoFilaInline
from .admin import TextoFotoInline
from .admin import TextoParametroInline
from .admin import TextoSeccionTextoFotoInline
from .admin import TextoSeccionTextoInline
from .carrusel import ImagenSeccionCarruselAdmin
from .carrusel import SeccionCarruselAdmin
from .carrusel import TextoImagenSeccionCarruselInline
from .carrusel import TextoSeccionCarruselInline
from .instalacion import FotoInstalacionInline
from .instalacion import SeccionInstalacionAdmin
from .instalacion import TextoFotoInstalacionInline
from .instalacion import TextoSeccionInstalacionInline
from .opcion import OpcionAdmin
from .opcion import TextoOpcionInline

