from .ContactoView import ContactoView
from .DetalleRetiroView import DetalleRetiroView
from .EventoView import EventoView
from .IndexView import IndexView
from .InstalacionDetalle import InstalacionDetalle
from .InstalacionesView import InstalacionesAmbientesView
from .InstalacionesView import InstalacionesCuartosView
from .QuienesSomosView import QuienesSomosView
from .RetiroView import RetiroView
from .ServicioView import ServiciosView
from .OpcionesView import OpcionesView
from .ToursView import ToursView
from .ViewBase import ViewBase
