from .ContactoView import ContactoView
from .IndexView import IndexView
from .InstalacionDetalle import InstalacionDetalle
from .InstalacionesView import InstalacionesAmbientesView
from .InstalacionesView import InstalacionesCuartosView
from .QuienesSomosView import QuienesSomosView
from .ServicioView import ServiciosView
from .ToursView import ToursView
from .ViewBase import ViewBase
